### ISSUE TITLE
ReadOnlyMemoryError

### ISSUE THREAD

**Issue by and2345** [JuliaGL/GLFW.jl#107] opened 2017-05-04 10:37 UTC
Hi, when I try to create a window using

`window = GLFW.CreateWindow(800, 600, "test")`

I get the following error:

`ERROR: LoadError: ReadOnlyMemoryError() in CreateWindow(::Int64, ::Int64, ::String, ::GLFW.Monitor, ::GLFW.Window) at /home/andreas/.julia/v0.5/GLFW/src/glfw3.jl:351`

Can you help me fix it? Thanks, Andreas

**Comment by jayschwa** [comment] 2017-05-05 15:15
Can you provide more context? Are you making any calls to GLFW before `CreateWindow`? What version of Julia are you using? What operating system are you using?

**Comment by and2345** [comment] 2017-05-05 16:00
Sorry, sure some context might be helpful...
I'm using julia v0.5.1 on Arch Linux and I'm not making any other calls to GLFW, just

`using GLFW; window = GLFW.CreateWindow(800, 600, "test")`

The error first showed up after I did a system update. I ran the same command on another (similar) one and it worked. So, this issue may not stem from GLFW.jl but from my system and if this is not the right place to discuss it, please let me know. But I'd be thankful for any help if you got an idea where this error comes from...

**Comment by jayschwa** [comment] 2017-06-28 18:17
I'm closing this issue since it sounds like it wasn't caused by GLFW.jl. Feel free to reopen if you now believe that GLFW.jl is the cause. Or add a note for future generations if you found the solution.

**Closed by jayschwa** 2017-06-28 18:17 UTC

**Comment by lucianolorenti** [comment] 2017-11-24 17:41
I am having  same problem with an Ubuntu 16.04 and a Archlinux. Both machines have an AMD gpu but different models. The [first example of GLFW](http://www.glfw.org/documentation.html)  works for me. I don't know what additional information should I provide

**Comment by jayschwa** [comment] 2017-11-24 18:29
So it works from C, but not Julia? Can you provide the Julia code that causes it, and the stack trace from the error?

**Comment by lucianolorenti** [comment] 2017-11-24 18:36
```
julia> using GLFW
julia> window = GLFW.CreateWindow(640, 480, "GLFW.jl")
ERROR: ReadOnlyMemoryError()
Stacktrace:
 [1] CreateWindow(::Int64, ::Int64, ::String, ::GLFW.Monitor, ::GLFW.Window) at /home/luciano/.julia/v0.6/GLFW/src/glfw3.jl:351 (repeats 2 times)

```
If I run the last line again
```
julia> window = GLFW.CreateWindow(640, 480, "GLFW.jl")

signal (11): Violación de segmento
while loading no file, in expression starting on line 0
unknown function (ip: 0x7fb04ed5eec9)
unknown function (ip: 0x7fb04eb8ed9d)
unknown function (ip: 0x7fb04ec28c3b)
unknown function (ip: 0x7fb04ec28d00)
unknown function (ip: 0x7fb04eb5e797)
unknown function (ip: 0x7fb0529a1eda)
glfwCreateWindow at /usr/lib/libglfw.so (unknown line)
CreateWindow at /home/luciano/.julia/v0.6/GLFW/src/glfw3.jl:351
CreateWindow at /home/luciano/.julia/v0.6/GLFW/src/glfw3.jl:351
unknown function (ip: 0x7fb056ee2993)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1933
do_call at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:75
eval at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:242
eval_body at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:543
jl_interpret_toplevel_thunk at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:692
jl_toplevel_eval_flex at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:592
jl_toplevel_eval_in at /home/centos/buildbot/slave/package_tarball64/build/src/builtins.c:496
eval at ./boot.jl:235
unknown function (ip: 0x7fb0734c239f)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1933
eval_user_input at ./REPL.jl:66
unknown function (ip: 0x7fb0735301cf)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1933
macro expansion at /home/luciano/.julia/v0.6/Revise/src/Revise.jl:775 [inlined]
#17 at ./event.jl:73
unknown function (ip: 0x7fb056ed7dcf)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1933
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/src/julia.h:1424 [inlined]
start_task at /home/centos/buildbot/slave/package_tarball64/build/src/task.c:267
unknown function (ip: 0xffffffffffffffff)
Allocations: 4549413 (Pool: 4547987; Big: 1426); GC: 8
Violación de segmento
```
dmesg say
`[ 5316.962956] julia[15387]: segfault at 10 ip 00007f90c0ca2eca sp 00007fff611fd020 error 4 in r600_dri.so[7f90c0a15000+98d000]
`

**Comment by SimonDanisch** [comment] 2017-11-24 18:48
Can you try julia-debug and maybe gdb? also, did you compile GLFW into your system image by any chance?
Those stack traces remind me of debugging static compilation issues...

**Comment by lucianolorenti** [comment] 2017-11-25 02:18
I have the same error whether I compile the library or I use the library located in deps. 

I compiled GLFW with debug symbols and in Julia fails in glfw-3.2.1/src/context.c:54
`glClear(GL_COLOR_BUFFER_BIT);`

**Comment by lucianolorenti** [comment] 2017-11-26 10:55
This issue @96 pointed me in the right direction. Apparently there is a problem when I compile julia with USE_SYSTEM_LLVM=1.  When Julia compiles their own LLVM I can create the window without problems.

**Comment by ihnorton** [comment] 2017-12-02 20:48
Also seeing this. Looks like the problem is with multiple libLLVM are loaded in the same address space due to MESA/llvmpipe as in #96, but it's happening on Julia 0.6.1 generic build.

x-ref: https://github.com/JuliaLang/julia/issues/19606

Before and after creating a Gtk GLArea with [this test script](https://github.com/JuliaGraphics/Gtk.jl/issues/336#issuecomment-348532506):
```
osboxes@osboxes:~$ pmap 7036 | grep -i llvm
00007f865432d000  27796K r-x-- libLLVM-3.9.so
00007f8655e52000   2048K ----- libLLVM-3.9.so
00007f8656052000   1324K r---- libLLVM-3.9.so
00007f865619d000     88K rw--- libLLVM-3.9.so
osboxes@osboxes:~$ pmap 7036 | grep -i llvm
00007f8624c83000  45000K r-x-- libLLVM-4.0.so.1
00007f8627875000      4K ----- libLLVM-4.0.so.1
00007f8627876000   3152K r---- libLLVM-4.0.so.1
00007f8627b8a000     20K rw--- libLLVM-4.0.so.1
00007f865432d000  27796K r-x-- libLLVM-3.9.so
00007f8655e52000   2048K ----- libLLVM-3.9.so
00007f8656052000   1324K r---- libLLVM-3.9.so
00007f865619d000     88K rw--- libLLVM-3.9.so
```

**Comment by SimonDanisch** [comment] 2017-12-04 18:05
@ihnorton I can't really reproduce this. What did you exactly do? I guess 7036 is the ID of the julia process? How do you keep it alive after the segfault?
I tried the fix from https://github.com/JuliaGL/GLFW.jl/issues/96 (setting `override USE_LLVM_SHLIB = 0`), but that also didn't help.

**Comment by jayschwa** [comment] 2017-12-04 18:12
This happens when Julia is compiled with certain parameters? Are you all building Julia yourselves or using prebuilt binaries? It seems like enough people have the issue that we should maybe add a blurb to the README about it, but I'd also like to figure out if there's some upstream issue to be raised.

**Comment by SimonDanisch** [comment] 2017-12-04 18:14
I'm building Julia myself and usually don't have any special parameters, but tried it now with `override USE_LLVM_SHLIB = 0`

**Comment by ihnorton** [comment] 2017-12-04 18:31
Sorry, I was about 5-7 bug depth into my evening at this point and was commenting here as a potential FYI rather than necessarily for help, should have been clear about that 😄  (and there may be multiple issues conflated here)

@jayschwa:

> This happens when Julia is compiled with certain parameters?

In my case, I believe it's because of using mesa/llvmpipe graphics (or potentially other libraries that use LLVM at the same time as Julia). See https://github.com/JuliaLang/julia/issues/19606

One work-around (for me) is to use LIBGL_ALWAYS_INDIRECT=1 but in real use that will probably be slow.

@SimonDanisch:

> What did you exactly do?

    window = GLFW.CreateWindow(800, 600, "test")

> I guess 7036 is the ID of the julia process?

Yes -- the example is just showing that a different version of libLLVM is loaded in the process after  starting.

> How do you keep it alive after the segfault?

gdb

**Comment by SimonDanisch** [comment] 2017-12-04 19:01
>  How do you keep it alive after the segfault?

> gdb

Ah okay, so I did everything like you, but my process doesn't load a different llvm, since I'm not actually using the llvmpipe graphics.
